### ISSUE TITLE
cz sk archiv

### ISSUE THREAD

**Issue by GoogleCodeExporter** [google-code-export/archivy-czsk#25]
```
zdravim po naistalovani pluginu toho nejnovejsiho  nejde naistalovat pise toto 
: extesions/archivCZSK(local variable manu referenced before assigment)     mam 
naistalovanou image hdmu 11505  nejnovejsi
```

Original issue reported on code.google.com by `patrikba...@gmail.com` on 20 Oct 2013 at 12:25

**Comment by GoogleCodeExporter** [comment]
```
Mám stejný problém. Nainstaloval Archivy jde (vypíše se, že bylo 
nainstalováno 6 balíčků), ale po restartu enigmy Archivy nejsou v 
základním menu. Po přechodu do menu Pluginů se vypíše uvedený text 
(local variable manu...).
```

Original comment by `range...@gmail.com` on 22 Oct 2013 at 12:36

**Comment by GoogleCodeExporter** [comment]
```
[deleted comment]
```

**Comment by GoogleCodeExporter** [comment]
```
Potreboval by som log pocas startu enigmy - AkoZiskatLog (pricom nenastala 
kriticka chyba).
```

Original comment by `mx3Lm...@gmail.com` on 22 Oct 2013 at 10:21

**Comment by GoogleCodeExporter** [comment]
```
+ (1) Background File Eraser
+ (5) Tuxtxt
+ (8) graphics acceleration manager
STMFB accel interface available

+ (9) GFBDC
15360k total video mem
7260k usable video mem
5640kB available for acceleration surfaces.
resolution: 720 x 576 x 32 (stride: 2880)
+ (9) gLCDDC
eDBoxLCD::eDBoxLCD >
Error loading config file!

LCD resolution: -1 x -1 x -1262715656 (stride: 1768452193)
+ (9) Font Render Class
[FONT] initializing lib...
[FONT] loading fonts...
[FONT] Intializing font cache, using max. 4MB...
+ (10) gRC
RC thread created successfully
+ (15) eWindowStyleManager
+ (20) DVB-CI UI
+ (20) RC Input layer
+ (20) misc options
+ (20) AVSwitch Driver
couldnt open /dev/dbox/fp0 to monitor vcr scart slow blanking changed!
+ (21) input device driver
Input device "fulan front panel buttons" is a remotecontrol
Input device "TDT RC event driver" is a remotecontrol
failed to open /dev/input/event2
Input device "" is a remotecontrol
failed to open /dev/input/event3
Input device "" is a remotecontrol
Found 4 input devices.
+ (22) Hdmi CEC driver
+ (30) eActionMap
+ (35) CI Slots
scanning for common interfaces..
eDVBCIInterfaces->setInputSource(0, 0)
eDVBCIInterfaces->setInputSource(1, 1)
done, found 0 common interface slots
+ (35) CA handler
+ (36) Stream server
[SERVERSOCKET] ERROR on bind() (Address already in use)
+ (40) eServiceCenter
settings instance.
+ (41) eServiceFactoryDVD
+ (41) eServiceFactoryEPlayer3
+ (41) eServiceFactoryM2TS
+ (41) eServiceFactoryMP3
+ (41) eServiceFactoryFS
+ (41) eServiceFactoryDVB
reached rl 70
---- opening lame channel db
reading services (version 4)
loaded 6444 services
scanning for frontends..
opening frontend 0
frontend successfully opened
close frontend 0
found 1 adapter, 1 frontends(1 sim) and 2 demux, boxtype 28
RTC not ready... wait for transponder time
[EPGC] Initialized EPGCache (wait for setCacheFile call now)
Loading spinners...
[ePNG] couldn't open /usr/local/share/enigma2/skin_default/spinner/wait13.png
found 12 spinner!

setIoPrio best-effort level 3 ok
Failed to open /dev/dbox/fp0
[Harddisk] enumerating block devices...
new Harddisk sda -> /dev/sda -> /dev/sda
main thread is non-idle! display spinner!
Reading satellites.xml
sec config cleared
setSlotInfo for dvb frontend 0 to slotid 0, descr STV090x Multistandard, need 
rotorworkaround No, enabled No, DVB-S2 Yes
slot: 0 configmode: nothing
sec config completed
loading bouquet... /etc/enigma2/bouquets.tv 1
loading bouquet... /etc/enigma2/userbouquet.mein_tv.tv 1
47 entries in Bouquet userbouquet.mein_tv.tv
loading bouquet... /etc/enigma2/userbouquet.hdtv.tv 48
36 entries in Bouquet userbouquet.hdtv.tv
loading bouquet... /etc/enigma2/userbouquet.sky_hdtv.tv 84
19 entries in Bouquet userbouquet.sky_hdtv.tv
loading bouquet... /etc/enigma2/userbouquet.sky_cinema.tv 103
10 entries in Bouquet userbouquet.sky_cinema.tv
loading bouquet... /etc/enigma2/userbouquet.sky__welt___extra.tv 113
35 entries in Bouquet userbouquet.sky__welt___extra.tv
loading bouquet... /etc/enigma2/userbouquet.sky_bundesliga.tv 148
21 entries in Bouquet userbouquet.sky_bundesliga.tv
loading bouquet... /etc/enigma2/userbouquet.sky_sport.tv 169
38 entries in Bouquet userbouquet.sky_sport.tv
loading bouquet... /etc/enigma2/userbouquet.austriasat.tv 207
13 entries in Bouquet userbouquet.austriasat.tv
loading bouquet... /etc/enigma2/userbouquet.kinder.tv 220
12 entries in Bouquet userbouquet.kinder.tv
loading bouquet... /etc/enigma2/userbouquet.musik.tv 232
16 entries in Bouquet userbouquet.musik.tv
loading bouquet... /etc/enigma2/userbouquet.oesterreich.tv 248
27 entries in Bouquet userbouquet.oesterreich.tv
loading bouquet... /etc/enigma2/userbouquet.italien.tv 275
89 entries in Bouquet userbouquet.italien.tv
loading bouquet... /etc/enigma2/userbouquet.schweiz.tv 364
20 entries in Bouquet userbouquet.schweiz.tv
loading bouquet... /etc/enigma2/userbouquet.holland.tv 384
23 entries in Bouquet userbouquet.holland.tv
loading bouquet... /etc/enigma2/userbouquet.sky_select.tv 407
14 entries in Bouquet userbouquet.sky_select.tv
loading bouquet... /etc/enigma2/userbouquet.xxx.tv 421
47 entries in Bouquet userbouquet.xxx.tv
loading bouquet... /etc/enigma2/userbouquet.favourites.tv 468
0 entries in Bouquet userbouquet.favourites.tv
17 entries in Bouquet bouquets.tv
loading bouquet... /etc/enigma2/bouquets.radio 1
loading bouquet... /etc/enigma2/userbouquet.deutsche.radio 1
19 entries in Bouquet userbouquet.deutsche.radio
loading bouquet... /etc/enigma2/userbouquet.favourites.radio 20
0 entries in Bouquet userbouquet.favourites.radio
2 entries in Bouquet bouquets.radio
[FONT] adding font /usr/local/share/fonts/nmsbd.ttf...OK (Regular)
[FONT] adding font /usr/local/share/fonts/andale.ttf...OK (Fixed)
[FONT] adding font /usr/local/share/fonts/goodtime.ttf...OK (Crs)
[FONT] adding font /usr/local/share/fonts/age.ttf...OK (Age)
[FONT] adding font /usr/local/share/fonts/tuxtxt.ttf...OK (Console)
[FONT] adding font /usr/local/share/fonts/time.ttf...OK (BMCTime)
[FONT] adding font /usr/local/share/fonts/ae_AlMateen.ttf...OK (Replacement)
3660kB available for acceleration surfaces.
resolution: 1280 x 720 x 32 (stride: 5120)
[FONT] adding font /usr/share/fonts/md_khmurabi_10.ttf...OK (Regular)
[FONT] adding font /usr/share/fonts/valis_lcd.ttf...OK (Digital)
[FONT] adding font /usr/local/share/fonts/valis_enigma.ttf...OK (Subs)
[FONT] adding font /usr/local/share/fonts/nmsbd.ttf...OK (FdLcD)
[iInputDevices] getInputDevices  <ERROR: ioctl(EVIOCGNAME): [Errno 19] No such 
device: '/dev/input/mouse3' >
[iInputDevices] getInputDevices  <ERROR: ioctl(EVIOCGNAME): [Errno 19] No such 
device: '/dev/input/mouse2' >
[iInputDevices] getInputDevices  <ERROR: ioctl(EVIOCGNAME): [Errno 19] No such 
device: '/dev/input/mouse1' >
[iInputDevices] getInputDevices  <ERROR: ioctl(EVIOCGNAME): [Errno 19] No such 
device: '/dev/input/mouse0' >
[iInputDevices] getInputDevices  <ERROR: ioctl(EVIOCGNAME): [Errno 19] No such 
device: '/dev/input/event3' >
[iInputDevices] getInputDevices  <ERROR: ioctl(EVIOCGNAME): [Errno 19] No such 
device: '/dev/input/event2' >
[iInputDevices] getInputDevices  <ERROR: ioctl(EVIOCGNAME): [Errno 22] Invalid 
argument >
[iInputDevices] getInputDevices  <ERROR: ioctl(EVIOCGNAME): [Errno 22] Invalid 
argument >
[iInputDevices] getInputDevices  <ERROR: ioctl(EVIOCGNAME): [Errno 19] No such 
device: '/dev/input/mice' >
[iInputDevices] getInputDevices  <ERROR: ioctl(EVIOCGNAME): [Errno 19] No such 
device: '/dev/input/js3' >
[iInputDevices] getInputDevices  <ERROR: ioctl(EVIOCGNAME): [Errno 19] No such 
device: '/dev/input/js2' >
[iInputDevices] getInputDevices  <ERROR: ioctl(EVIOCGNAME): [Errno 19] No such 
device: '/dev/input/js1' >
[iInputDevices] getInputDevices  <ERROR: ioctl(EVIOCGNAME): [Errno 19] No such 
device: '/dev/input/js0' >
Selected keymap does not exist!
Activating language ÄŚesky
[ePopen] command: ip -o addr show dev eth0
eDBoxLCD::getInstance
loadSkin: Screen already defined elsewhere: HDMU_MainMenu
loadSkin: Screen already defined elsewhere: HDMU_SoftcamControl
loadSkin: Screen already defined elsewhere: HDMU_OverclockControl
loadSkin: Screen already defined elsewhere: HDMU_SystemControl
loadSkin: Screen already defined elsewhere: HDMU_SystemInfos
loadSkin: Screen already defined elsewhere: HDMU_ufsup
loadSkin: Screen already defined elsewhere: HDMU_OSDControl
loadSkin: Screen already defined elsewhere: HDMU_VFDControl
loadSkin: Screen already defined elsewhere: HDMU_VideoControl
loadSkin: Screen already defined elsewhere: HDMU_DLNAServer
loadSkin: Screen already defined elsewhere: HDMU_OpenVPN
loadSkin: Screen already defined elsewhere: HDMU_SkinControl
[WebInterface] set language to  cs
[WebInterface] set language to  cs
[WebInterface] fallback to default translation for Webinterface
[WebInterface] fallback to default translation for Configuration for the 
Webinterface
[WebInterface] set language to  cs
found gstreamer
Plugin  Extensions/archivCZSK failed to load: local variable 'manu' referenced 
before assignment
Traceback (most recent call last):
  File "usr/lib/enigma2/python/Components/PluginComponent.py", line 52, in readPluginList
  File "usr/lib/enigma2/python/Tools/Import.py", line 2, in my_import
  File "/usr/lib/enigma2/python/Plugins/Extensions/archivCZSK/plugin.py", line 13, in <module>
    import gui.download as dwnld
  File "/usr/lib/enigma2/python/Plugins/Extensions/archivCZSK/gui/download.py", line 25, in <module>
    from base import  BaseArchivCZSKScreen, BaseArchivCZSKMenuListScreen
  File "/usr/lib/enigma2/python/Plugins/Extensions/archivCZSK/gui/base.py", line 16, in <module>
    from common import PanelList, PanelListEntryHD, PanelListEntrySD
  File "/usr/lib/enigma2/python/Plugins/Extensions/archivCZSK/gui/common.py", line 19, in <module>
    from Plugins.Extensions.archivCZSK import settings, _
  File "/usr/lib/enigma2/python/Plugins/Extensions/archivCZSK/settings.py", line 27, in <module>
    (MANUFACTURER, MODEL, ARCH, VERSION) = stb.getBoxtype()
  File "/usr/lib/enigma2/python/Plugins/Extensions/archivCZSK/engine/tools/stb.py", line 17, in getBoxtype
    _setBoxtype()
  File "/usr/lib/enigma2/python/Plugins/Extensions/archivCZSK/engine/tools/stb.py", line 105, in _setBoxtype
    gBoxType = (manu, model, arch, version)
UnboundLocalError: local variable 'manu' referenced before assignment
[eSocketMMIHandler] created successfully
getModeList for port Component
getModeList for port Scart
getModeList for port HDMI
getModeList for port HDMI-PC
hotplug on dvi
-> setting aspect, policy, policy2, wss any bestfit policy auto
-> setting aspect, policy, policy2, wss any bestfit policy auto
-> setting aspect, policy, policy2, wss any bestfit policy auto
-> setting aspect, policy, policy2, wss any bestfit policy auto
setMode - port: Scart mode: PAL rate: 50Hz
-> setting aspect, policy, policy2, wss any bestfit policy auto
updateColor:  Scart
LINE #  automatically   generated   by  enigma  2
LINE 
[AutoMount.py] self.automounts without mounts {}
[NetworkBrowser] fallback to default translation for NetworkBrowser
[NetworkBrowser] fallback to default translation for Search for network shares
[NetworkBrowser] fallback to default translation for MountManager
[NetworkBrowser] fallback to default translation for Manage network shares
starting hotplug handler
adding Resource DiseqcTester
resources: {'DiseqcTester': <function DiseqcTesterMain at 0x152fbc4>}
self.input oscam6666
[Toplevel.importExternalModules] Imported external module: Example
[HTTPRootResource}.__init__
[Webinterface] started on 0.0.0.0:80 auth=False ssl=False
[WebInterface.registerBonjourService] No module named Bonjour.Bonjour
[HTTPRootResource}.__init__
[Webinterface] started on 0.0.0.0:443 auth=True ssl=True
[WebInterface.registerBonjourService] No module named Bonjour.Bonjour
[EPGC] setCacheFile read/write epg data from/to '/hdd/epg.dat'
[SKIN] Parsing embedded skin <embedded-in-'Screensaver'>
warning, skin is missing element boquet in <class 
'Screens.ChannelSelection.ChannelSelection'>
warning, skin is missing element RassLogo in <class 
'Screens.RdsDisplay.RdsInfoDisplay'>
[SKIN] No skin to read...
warning, skin is missing element UnhandledKeyPixmap in <class 
'Screens.UnhandledKey.UnhandledKey'>
warning, skin is missing element From in <class 'Screens.Dish.Dish'>
warning, skin is missing element Goto in <class 'Screens.Dish.Dish'>
warning, skin is missing element tunerName in <class 'Screens.Dish.Dish'>
warning, skin is missing element turnSpeed in <class 'Screens.Dish.Dish'>
warning, skin is missing element posGoto in <class 'Screens.Dish.Dish'>
warning, skin is missing element posFrom in <class 'Screens.Dish.Dish'>
warning, skin is missing element turnTime in <class 'Screens.Dish.Dish'>
RemovePopup, id = ZapError
setValue 50
Setvolume: 50 50 (raw)
Setvolume: 32 32 (-1db)
child has terminated
pipes closed
[ePopen] command: route -n | grep  eth0
poll: unhandled POLLERR/HUP/NVAL for fd 30(16)
child has terminated
pipes closed
192.168
0.0.0.0
nameservers: [[10, 0, 0, 1]]
read configured interface: {'lo': {'dhcp': False}, 'wlan0': {'dhcp': True}, 
'eth0': {'dhcp': True}}
self.ifaces after loading: {'eth0': {'preup': False, 'predown': False, 'ip': 
[192, 168, 1, 129], 'up': True, 'mac': '24:00:0a:00:02:08', 'dhcp': True, 
'bcast': [192, 168, 1, 255], 'netmask': [255, 255, 255, 0], 'gateway': [192, 
168, 1, 254]}}
poll: unhandled POLLERR/HUP/NVAL for fd 35(16)

```

Original comment by `wilownat...@gmail.com` on 22 Oct 2013 at 4:01

**Comment by GoogleCodeExporter** [comment]
```
This issue was closed by revision r393.
```

Original comment by `mx3Lm...@gmail.com` on 23 Oct 2013 at 7:02
- Changed state: **Fixed**

**Comment by GoogleCodeExporter** [comment]
```
dakujem za log, oprava je zahrnuta v beta2 verzii
```

Original comment by `mx3Lm...@gmail.com` on 23 Oct 2013 at 5:42

**Comment by GoogleCodeExporter** [comment]
```
Taky děkuji že plugin funguje
```

Original comment by `patrikba...@gmail.com` on 24 Oct 2013 at 6:32
